### ISSUE TITLE
Secondlife (LindenLabs) login servers returning expected content

### ISSUE THREAD

**Issue by Madpeterz** [cinderblocks/libremetaverse#55]
```
237 [8] WARN  - Login response failure: Notation LLSD parsing: Unknown type marker 'S'.    at OpenMetaverse.StructuredData.OSDParser.DeserializeLLSDNotationElement(StringReader reader) in D:\VS projects\BetterSecondBot\LibreMetaverse.StructuredData\LLSD\NotationLLSD.cs:line 272
   at OpenMetaverse.StructuredData.OSDParser.DeserializeLLSDNotation(StringReader reader) in D:\VS projects\BetterSecondBot\LibreMetaverse.StructuredData\LLSD\NotationLLSD.cs:line 86
   at OpenMetaverse.StructuredData.OSDParser.DeserializeLLSDNotation(String notationData) in D:\VS projects\BetterSecondBot\LibreMetaverse.StructuredData\LLSD\NotationLLSD.cs:line 79
   at OpenMetaverse.LoginResponseData.Parse(Hashtable reply) in D:\VS projects\BetterSecondBot\LibreMetaverse\Login.cs:line 468
   at OpenMetaverse.NetworkManager.LoginReplyXmlRpcHandler(XmlRpcResponse response, LoginParams context) in D:\VS projects\BetterSecondBot\LibreMetaverse\Login.cs:line 1354
```
   
 Issue started as part of [Second Life Login Maintenance]( https://status.secondlifegrid.net/incidents/5r9n3t7dq1pt)

not sure if just broken login servers yet or if they changed something.

Issue seems to also affect [Lumiya](https://community.secondlife.com/forums/topic/479856-deploy-plan-for-the-weeks-of-2021-11-22-and-2021-11-29/?do=findComment&comment=2385066)

**Comment by Madpeterz** [comment]
ah there was a update that I was missing :P
